apiVersion: v1
kind: ConfigMap
metadata:
  name: "myapp-config"
  namespace: "myapp"
  labels:  
    app: "myapp"
    release: "__MYAPP_LABELS_RELEASE__"
    grafana_dashboard: "__MYAPP_GRAFANA_DASHBOARD__"
data:
  # elasticsearch
  ELASTICSEARCH_CLUSTER_NAME: "__ELASTICSEARCH_CLUSTER_NAME__"
  ELASTICSEARCH_TRANSPORT_ADDRESSES: "__ELASTICSEARCH_TRANSPORT_ADDRESSES__"
  ELASTICSEARCH_USER: "__ELASTICSEARCH_USER__"
  ELASTICSEARCH_SCROLL_THRESHOLD: "__ELASTICSEARCH_SCROLL_THRESHOLD__"
  ELASTICSEARCH_SCROLL_SIZE: "__ELASTICSEARCH_SCROLL_SIZE__"
  ELASTICSEARCH_SCROLL_KEEPALIVE: "__ELASTICSEARCH_SCROLL_KEEPALIVE__"
  # kafka
  KAFKA_CLUSTER_NAME: "__KAFKA_CLUSTER_NAME__"
  KAFKA_CLUSTER_BROKER_LIST: "__KAFKA_CLUSTER_BROKER_LIST__"
  # DATABASEFOO
  DATABASEFOO_SCHEMA: "__DATABASEFOO_SCHEMA__"
  DATABASEFOO_URL: "__DATABASEFOO_URL__"
  DATABASEFOO_USER: "__DATABASEFOO_USER__"
  # misc
  HTTP_INTERFACE: "__HTTP_INTERFACE__"
  HTTP_PORT: "__HTTP_PORT__"
  NODE_ID: "__NODE_ID__"
  # etc
  # ...